# Generated by Django 3.2.7 on 2021-09-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='job',
            name='test',
        ),
        migrations.AddField(
            model_name='job',
            name='decscription',
            field=models.TextField(default='Null Value', max_length=1000),
        ),
    ]
