# Generated by Django 3.2.7 on 2021-10-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_apply_jobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applied_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
