# Generated by Django 3.2.7 on 2021-10-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_apply_applied_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='jobID',
        ),
    ]
