# Generated by Django 3.2.7 on 2021-10-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_remove_apply_jobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='jobID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
            preserve_default=False,
        ),
    ]
